feat: update SEC to CAPI v1.14.1
ShipEngine/connect pull request #67
Opened 2021-03-18 21:53 UTC by dougwile

update carrier-api package with capi spec changes

2021-03-22 15:06 UTC, lzhang commented on packages/shipping-runtime/package.json
> +		"@shipengine/connect-sdk": "file:../sdk",
This should be unnecessary...

2021-03-22 16:03 UTC, jamesbar2 commented on packages/carrier-api/src/requests/create-label-request.ts
> +  DocumentFormat,
Should this be plural to match the others?

2021-03-22 16:09 UTC, dougwile commented on packages/carrier-api/src/requests/create-label-request.ts
> +  DocumentFormat,
Ah didn't realize that this project adopted plural names for enums. Gross. Consistency is more important than how much I hate plural enum names, so I'll update

2021-03-22 17:20 UTC, jeversmann-shipstation requested changes
🤔 a bunch of the `carrier-api` changes in here are breaking; since the swagger change wasn't Major we shouldn't be breaking the TS lib either, even if it means retaining some mismatched names.

2021-03-22 17:20 UTC, jeversmann-shipstation commented on packages/sdk/src/internal/carriers/pickups/shipped-package.ts
> +export interface ShippedPackagePOJO extends PackageIdentifierPOJO {
Renaming this is a breaking change.

2021-03-22 21:15 UTC, jeversmann-shipstation commented on packages/carrier-api/src/requests/get-rates-request.ts
> +  pickup_location: PudoLocation;
This needs a `?`

2021-03-22 21:15 UTC, jeversmann-shipstation commented on packages/sdk/src/internal/carriers/pickups/shipped-package.ts
> +  packaging: PackagingIdentifierPOJO | string;
This should probably have a `?` to match the public interface.

2021-03-22 21:15 UTC, jeversmann-shipstation commented on packages/carrier-api/src/models/pickup/shipped-shipment.ts
> +export interface ShippedShipment extends Label {
This looks like it also needs to extend `PickupShipment` somehow, so that we're not breaking `PickupShipmentDetails`

2021-03-22 21:44 UTC, lzhang commented
Fixup those conflicts brother

2021-03-22 21:44 UTC, dougwile commented on packages/carrier-api/src/models/pickup/shipped-shipment.ts
> +export interface ShippedShipment extends Label {
I left `PickupShipmentDetails` entirely alone, so it shouldn't be interacting with ShippedShipment or Label at all now

2021-03-22 22:06 UTC, dougwile commented on packages/carrier-api/src/models/addresses/pudo-location.ts
> +export interface PudoLocation extends AddressBase {
This is what it's called in CAPI. It isn't just pickup locations, but also dropoff locations. Doesn't matter much since this will all be revisited when we rev SEC

2021-03-23 15:37 UTC, jeversmann-shipstation commented
You need to update the swagger that's stored with the shipping runtime to the new spec so the redoc has the new fields, and update the website pages so the Connect docs reflect the changes to the SDK.

2021-03-23 18:12 UTC, lzhang commented
This deleted all the examples in the spec.yaml?

2021-03-23 20:08 UTC, jamesbar2 commented
I believe these examples are from 1.12 spec and before, there have been lots of deprecations.  We can follow on with examples so we can unblock devs.

2021-03-23 21:06 UTC, jeversmann-shipstation approved these changes
![](https://media.giphy.com/media/RkHFMsU5mzvNf4m2jX/giphy.gif)

2021-03-23 21:06 UTC, jeversmann-shipstation commented on website/src/pages/docs/reference/methods/create-manifest.mdx
> +          * `lb` for pounds
lol
<img width="490" alt="Screen Shot 2021-03-23 at 4 03 59 PM" src="https://user-images.githubusercontent.com/49000234/112218205-79191c00-8bf1-11eb-9a3c-28a622c0ec6d.png">

2021-03-23 21:38 UTC, dougwile commented
release carrier-api,sdk,shipping-runtime minor

2021-03-23 21:48 UTC, jeversmann-shipstation commented
release connect,loader minor

2021-03-23 21:56 UTC, ricky commented
release

2021-03-23 21:58 UTC, ricky commented
release all

2021-03-23 22:08 UTC, ricky approved these changes

2021-03-23 22:52 UTC, merged